import { chromium } from "playwright";
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
await page.goto("http://localhost:3000/masuk", { waitUntil: "domcontentloaded" });
await page.waitForSelector("text=Pilihan Akun Demo Instan", { timeout: 15000 });
await page.click('button:has-text("verifier@mboyo.demo")');
await page.click('button[type="submit"]');
await page.waitForURL(/verifier/, { timeout: 20000 });
await page.goto("http://localhost:3000/verifier/antrean", { waitUntil: "domcontentloaded" });
await page.waitForSelector("text=Antrean Verifikasi", { timeout: 15000 });
console.log(await page.locator("text=laporan menunggu tinjauan").innerText());
await browser.close();
